### ISSUE TITLE
Check Levelstats

### ISSUE THREAD

**Issue by maccxs** [youvsvirus/youvsvirus-unity#108]
When I played explore first, then campaing, there was an error with a levelstats object. Not reproducable at a first try. If we do not need the levelstats in the other level, we should maybe deactivate them? Or at least make sure that they do not interfere.

**Comment by holke** [comment]
What exactly was the error?

I also had a strange bug right now:
I lost the mask level and pressed "Main Menu". I then started the campain again and within like 5 seconds of playing the game ended and showed me the end screen from the sandbox mode.

Is this related to your experience?
