### ISSUE TITLE
End screen for all level

### ISSUE THREAD

**Issue by maccxs** [youvsvirus/youvsvirus-unity#111]
The screen to go to when leveldisco ends. Do we want points?
* points for each not infected NPC (which also reflects the time the player took to finish)
* points for each collected mask
* points for succeeding on first / second / third try?
* ...

**Comment by holke** [comment]
Many ideas.
Shall we do something simple for the next release?
Just a "You made it, thank you for playing" message or so?
And then work on a point system for the next release?

**Comment by maccxs** [comment]
That is probably a good idea if we want to get done this century. :-)

Am Fr., 22. Mai 2020 um 17:00 Uhr schrieb holke <notifications@github.com>:

**Comment by maccxs** [comment]
Added a protype of a an end screen for all levels in the current branch that you review. I am not set on the layout or the text, change at will.

**Comment by holke** [comment]
I like add.

We could add a "Stay safe" message at the end.

**Comment by maccxs** [comment]
Added possible message in https://github.com/youvsvirus/youvsvirus-unity/pull/126/commits/58a470119e8874bc3e3dcf588dfbc59bef4a0460

**Comment by maccxs** [comment]
Do you have something to add? Otherwise you can close.
