### ISSUE TITLE
Player house bug

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#123]
In the mask level: If i press space often and quickly while standing next to the player house, i can reach a state
where the player is inside and outside at the same time:
![image](https://user-images.githubusercontent.com/7125317/82813929-61202100-9e96-11ea-9d82-5c8675ec6fac.png)

The player can move around normally, but also the small player looks out of the window.

**Comment by holke** [comment]
I  thought this happened when the coroutine for entering and the one for exiting the house are called simultaneously.
In 5b5085c i changed the coroutines such that they cannot be executed if the other one is still running.
This seemed to make the bug occur less often, but it still occurs.

**Comment by maccxs** [comment]
Thanks for the picture. I somehow missed this issue altogether :-( Now I finally know what you mean. Sorry for seeing this so late.

**Comment by maccxs** [comment]
Were you able to fix it now with your idea?

**Comment by maccxs** [comment]
I just now saw your long comment about it. Sorry, am a bit distracted this week.

**Comment by holke** [comment]
Solved with the new house prefab.
