### ISSUE TITLE
Merge open branches

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#133]
Hi Margrit,

i think all branches currently in review can be merged.
i.e.
Margrit/design
Margrit/discolevel finetune
Leveldemo2
Using from now on q as exit key

Since i lost track of what is build upon what and hence would probably mess up the procces, i suggest that you do the merging.

**Comment by maccxs** [comment]
Sorry :-(

**Comment by holke** [comment]
Nono, no reason to be sorry. 
I just needed to state this Southgate you do not sit around and wait for me to merge.
