### ISSUE TITLE
Face mask for player?

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#137]
I just had a kind of epiphany: In the real world it is the law that we wear face masks when we go to the supermarket. But in the game, we do not let our player wear one, not setting a good example :(

Shall we quickly change it before the release? Just adding a mask to the player in the supermarket level?

**Comment by maccxs** [comment]
Nein, ich denke das ist nicht nötig, oder? Ich setze die super die Maske auch mal auf wenn ich im Supermarkt bin und nicht wenn ich auf dem Weg dorthin bin. Höchstens in der Disco könnte er eine Maske tragen. 
Von meinem Telefon gesendet

**Comment by maccxs** [comment]
On it
