### ISSUE TITLE
Whats with the EndScreen scene

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#152]
Do we need the scene main/EndScreen?

I think it is not included in the game and looks suspiciously familiar to the Sandbox/EndScreenSandbox scene.
I was just confused about it when looking through all scenes.

**Comment by maccxs** [comment]
We do not need it.

**Comment by maccxs** [comment]
Can we close this? Did we delete the scene?

**Comment by holke** [comment]
See #166
