### ISSUE TITLE
Check level supermarket

### ISSUE THREAD

**Issue by maccxs** [youvsvirus/youvsvirus-unity#155]
(1) Bei einem Versuch haben sich 2 Emojis am linken Ende der Severinsbrücke "verkeilt" und so die Brücke blockiert.
(2) Von den Poller Wiesen gelangt der Spieler unterhalb der Severinsbrücke nach Deutz (ohne die Brücke zu benutzen.

Despite prevention measures it may happen that two emojis block each other. In my opinion I would not do anything about it since it happens rarely only. The second comment I will definitely check out.

**Comment by maccxs** [comment]
2 should be solved in the corona glasses branch

**Comment by holke** [comment]
Yes it is
