### ISSUE TITLE
Implement social distancing factor

### ISSUE THREAD

**Issue by maccxs** [youvsvirus/youvsvirus-unity#17]

**Comment by holke** [comment]
Social distancing is now also applied to the player which seems kind of weird to me.
Is this a bug that you will fix or is it intentional?

**Comment by maccxs** [comment]
@holke @FredyHennig I am playing with sd at the moment. The player is no longer affected since i do no longer adjust the collider radius. However, if i decreas the velocity as suggested by @FredyHennig the smileys are togehter for a longer time, since the collision implemented in unity is dependent on the velocity (which is sensible). So if we do not want this, our other option wold be not to use the physics engine which would be a mayor change. Or try to avoid collisions which I will try to do first.

**Comment by maccxs** [comment]
So here is what I though: If the velocity becomes too slow I simply decrease the mass so that the impulse stays the same. Laws of nature bow before me.

**Comment by maccxs** [comment]
@FredyHennig @holke 
The social distancing stuff ist not really working out so well. What I tried so far: 
* let the smileys move slower for social distancing --> collisions with less impulse, smileys stick together
* adapt the mass to make collision more forceful, but this then also has an influence on other stuff, which I am not really sure about, but which leads to a suboptimal result
* tried to adapt bounciness and friction of collider material, could have a little effect
* tried to raycast to see other npcs ... then move somewhere else, but this also makes them huddle together in small groups
* even tried to switch from dynamic to kinematic but my knowledge is too small and my patience too thin to see this through at the moment
* was fun but for today my ideas are gone so if anyone has an idea... feel free to post or implement

**Comment by maccxs** [comment]
Ok, I have one or two more ideas to try out today. :-)  Maybe something will stick.
