### ISSUE TITLE
Adapt smiley size for more variety.

### ISSUE THREAD

**Issue by maccxs** [youvsvirus/youvsvirus-unity#31]
See discussion on team site.

**Comment by maccxs** [comment]
Hey @FredyHennig A size of 0.12 x 0.12 x 0.8  was quite good I thought. What bugs me a little: The images themselves are a little different: the player smiley and the blue smilyes seem smaller than the other one.

**Comment by holke** [comment]
@maccxs @FredyHennig if you did not do so already, i could change the size of the images.

**Comment by ghost** [comment]
@holke I rescaled all the images to 512x512 pixels some time ago, so the sprites should all be the same size. But @maccxs , you're right, the exposed and recovered smileys do not extend to the edge of their sprites, so they appear smaller.  

To me, 0.12 appears a little bit too large. How about 0.08 for the NPCs and 0.1 for the player?

**Comment by ghost** [comment]
I fixed the smileys, check it out in the frederik/smallerSmileys branch.

**Comment by maccxs** [comment]
I like it! Can we merge this into the master?

**Comment by ghost** [comment]
Sure we can :)
