### ISSUE TITLE
Sliders do nothing after restart

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#33]
When we use the "Neustart" Button from the End Screen, the sliders do not change the game behaviour anymore :(
Even if we do not keep the Neustart feature in the final version it would be very useful for debugging though.

**Comment by maccxs** [comment]
@holke If I press the start button things change after neustart

**Comment by ghost** [comment]
@holke Although I can't reproduce the bug, I have an idea about the origin of the problem: Check out my review on the endscreen PR. The reason should be the duplicate creation of the LevelSettings game object, but the singleton getter I implemented in LevelSettings.cs should already solve this issue...

Still, I'm fixing the duplicate creation, just to be sure.

**Comment by holke** [comment]
Yes your Fix for the duplication also seems to resolve this bug.
