### ISSUE TITLE
Testing before release

### ISSUE THREAD

**Issue by maccxs** [youvsvirus/youvsvirus-unity#53]
Do some playing before the release, make some small fixes, no new features. Maybe create an executable or web test version after #52, #50 and #49 have been merged and invite the other developers to test.

**Comment by ghost** [comment]
As I have already written in #52, we should disable full screen mode for our first release and have the player canvas size fixed. This is the best way around the map scaling issues we have at the moment, when working with oddly sized viewports and changing viewport aspect ratios.

**Comment by holke** [comment]
I honestly do not think that full screen is such an issue.
The map is not exactly the same in full screen and the white borders are visible.
But this does not affect the "gameability".

Or is there a more serious issue that i cannot see on my laptop?

**Comment by ghost** [comment]
It's doesn't really affect gameplay. Only when you start the game in fullscreen and then switch to window mode, the map is larger than the viewport and the player might move out of sight. It's not perfect, but also not seriously broken. I'd still vote to disable fullscreen; these things tend to confuse players.

Everything else looks fine to me, I guess we can release it now.

**Comment by maccxs** [comment]
@ FredyHennig: I think we should start fine tuning the radius for the infection model afterwards. If we leave it like it is at the moment in some configurations nothing will happen, which is perhaps a little boring.

**Comment by holke** [comment]
I tested the final version now and think it is ready for release.

**Comment by ghost** [comment]
@maccxs You're right. I am working on an implementation of social distancing without larger colliders, but with a 'comfort zone' and with NPCs actively trying to avoid each other. I'd also make the infection radius dependent on social distancing. This should be a lot more fun, since NPCs can still come into contact and infect each other in crowded areas this way.

**Comment by maccxs** [comment]
Ok, then let's just release or take the old verision before your introduced r? What do you think?

**Comment by maccxs** [comment]
I somehow really like the full screen mode. The smileys do not leave the screen, rather they stay more inside than expected

**Comment by maccxs** [comment]
For me in non-fullscreen mode the smileys leave the map

**Comment by maccxs** [comment]
Ok so my final fity cents: **Do not use the new radius** but merge my pull request with the old one. Maybe **@holke  should do the web build** if both the full screen and the normal version look good for him (in my version the smileys leave in the non-fullscreen and in @FredyHennig's in the full screen). How do we integrate in on the web page after that?

**Comment by maccxs** [comment]
But then again, every option is fine as long as the smileys do not leave the map and the radius thing is not that important. I am sorry, I am very tired I guess

**Comment by maccxs** [comment]
Ok, Firefox: Everything's fine. Edge: Some smileys leave. Let's just release it

**Comment by maccxs** [comment]
I will stop doing anything now. If you want to take action, do it. Otherwise I will take care of the relase tomorrow. Goodnight, thanks for all the work. And sorry for the many weird comments above ;-)

**Comment by ghost** [comment]
Yes, let's just do it. I built the WebAssembly binaries and created the release draft [here](https://github.com/youvsvirus/youvsvirus-unity/releases), but I'll leave the honor of pressing "publish" to you. 

Now we just need to embed it into the website.

**Comment by holke** [comment]
I agree with both of you.
Let’s put it out there and then polish it afterwards.
Looking forward to the release :)
