### ISSUE TITLE
Put game on website

### ISSUE THREAD

**Issue by maccxs** [youvsvirus/youvsvirus-unity#59]
Hey Thomas,

can you put the game https://github.com/youvsvirus/youvsvirus-unity/releases on the website?

It took a little longer than expected and is still only the first version of hopefully more levels to come.

Thanks
Margrit

**Comment by maccxs** [comment]
@ThomasVoss will do this on the weekend

**Comment by maccxs** [comment]
I will make a prototype website for Thomas with our webgl content

**Comment by ThomasVoss** [comment]
first test indicate that works like a charm.

**Comment by maccxs** [comment]
Hompage ist online.
