### ISSUE TITLE
More levels

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#61]
Add more levels to the game.

Ideas:

Level 1 (the current state): Move around and try not o get infected. Maybe we can end this after n seconds? like: Survive for 1 Minute?

Level 2: Move to you house at the opposite end of the map.

Level 3: There is a supermarket on the map. Go there and get back to your house again.
The supermarket should be visited by other NPCs too.

Level 4 (sophisticated, needs new map): Inside the supermarket. Get item X and get out. The NPCs move along the aisles.

Do you have more ideas? Please feel free to add here or to the [discussion thread.]( https://github.com/orgs/youvsvirus/teams/game-developers)

**Comment by maccxs** [comment]
Level 2.1: Save the people at risk.
A number of old npcs (moving slow) or some otherwise ill or smoking npcs (all with a high probability of dying) have to be saved by the player from getting infected.

**Comment by holke** [comment]
Good idea, but how do we save an npc?

**Comment by maccxs** [comment]
Maybe as a first unsophisticated step jush push the others away, the risk patients have to survive for 30s.

**Comment by maccxs** [comment]
Level 5: Collect and distribute masks.

**Comment by maccxs** [comment]
Maybe the player gets points for 
* completing a level 50
* \- 10 for each dead
* \- 1 for each infected
* +5 for each unexposed
or the like

**Comment by holke** [comment]
Yes points are good.
However, we need to incorporate the social distancing and number of people settings. 
Otherwise I just set SD to 100 and get all the points.

Edit: number of people is easy if you get points for noninfected. I.e. you can never get more than 10 points if you only have 10 NPCs

**Comment by holke** [comment]
I honestly do not like the idea of pushing others away. Translated to the real world this would mean encouraging people to violence when they go outside and see someone close to an elder person... :/

**Comment by maccxs** [comment]
I encourage violence a lot. In myself and others ;-)

**Comment by maccxs** [comment]
Maybe just distribute masks so that the old people do not get infected. And go to the supermarket for them.

**Comment by holke** [comment]
Please see #73 for my ongoing experiments on this.

How do we transition between levels?
I suggest: One Intro Screen telling the user what to do in this level.
Then the level.
After the level an end screen printing stats/points etc. and a continue button that leads the user to the intro screen of the next level.

**Comment by holke** [comment]
A subissue that arises:

For new levels we mostly copy the first level.
How can we ensure that changes made to this level that we want in the new ones are actually also applied?

For example: Margrit is currently working on the edge colliders for the map. She is working on a branch that only have level 1.
On a different branch we copied level 1 to create levels 2 and 3.
Once we integrate both changes we will probably have the problem that the edged colliders are only applied to level 1 and not the other levels as well as they should be.
