### ISSUE TITLE
License

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#71]
Add a licence to the code.
Which one?
Do you all agree with LGPL? Thus, everybody is allowed to use it as he wants, even to generate money.
Or GPL2. Everybody is allowed to use it, but must make all theri code open source (which often permits people from making money off it).

**Comment by maccxs** [comment]
No opinion. No experience. Sorry.

**Comment by maccxs** [comment]
GPL2 ?

**Comment by holke** [comment]
Why not.
I will add it then.

**Comment by holke** [comment]
Done.

I added GPL v3 license and pushed it directly to master.
If you agree, just close this issue.
