### ISSUE TITLE
How are infected/killed by you counted?

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#72]
Are these counted as the people i infected personally or also as the people that were infected by people that i infected etc.?
I think it is the former, but it should be the latter.
Please check and change if needed.

**Comment by maccxs** [comment]
It is only those that i infected personally.

**Comment by holke** [comment]
Thanks for checking!
Should we change it then?
To understand the consequences of the players decision, people that die because they had contact with someone I infected should count as well, shouldnt they?

**Comment by maccxs** [comment]
yes
