### ISSUE TITLE
Give the human and NPCs a home 

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#74]
Add a picture of a house or better multiple houses, where the player and the NPCs can live.
These pictures can then be used in level design.

**Comment by maccxs** [comment]
Multiple NPCs should live in one home, otherwise we clutter the map with houses.
We could have single persons or families with kids live there, maybe add a high storage building where, even more can live.

**Comment by maccxs** [comment]
See a1803cabea6529d9b08896de0580dd28361f118a for an example.

**Comment by maccxs** [comment]
Maybe also add a hospital?

**Comment by maccxs** [comment]
I added a hospital in the same folder of that branch. The num of smileys at home and in the hospital could be variable, so one picture for each possibility. The NPCs would then be invisible once they enter the house, instead the picture of the house would show up with the appropriate num of smileys. Or the hospital.

**Comment by maccxs** [comment]
If this is reasonable I can provide pics for all these possibilities.

**Comment by maccxs** [comment]
A more fancy variant is also provided in the folder. Maybe I like that even better.

**Comment by maccxs** [comment]
AdditionalData/fancyHouses4Smileys.png

**Comment by maccxs** [comment]
I will open a new branch for this.

**Comment by holke** [comment]
Nice! I especially like the colored houses.
I fear that the hospital with only black outlines is not really visible on the map, though.

**Comment by maccxs** [comment]
I provided the fancy colored houses with up to 8 inhabitants. But then I thought, well, this already takes a lot of time. How about we add the player and then the player gets infected, need separate house for that, then infected smiley, another house for that, another infected smiley.... this will never stop! 
What we have to do: 
If NPC touches door to come home:
- make npc disappear
- get condition of npc
- make sprite (not npc itself) appear in window depending on npc condition

Same for the house of the player. I could provide the house and the windows separately which looks quite nice when you place the sprite behind the house and before the window (see exampels 1...8). It would also be easy to add more similar houses in different color. I would only place 2 smileys in one window, not 4 (see examples).

**Comment by holke** [comment]
Having extra sprites for each NPC in a home indeed takes a lot of time.

Why not make this simpler? The NPC move to its house and when its there it does not vanish but just stays on top of the house?

**Comment by maccxs** [comment]
On top of the house? On the roof?

**Comment by maccxs** [comment]
Added hospital

**Comment by holke** [comment]
Like on top of the sprite as seen from the camera view.
This
````
/    \
| :) |
|__ _|
````
Not this

````
  :)
/    \
|    |
|__ _|
````

**Comment by maccxs** [comment]
But my way looks better ;-)

**Comment by maccxs** [comment]
Making the sprite vanish is no real problem, you only have to change their layer and stop their movement as if they were dead and invisible. 
But maybe I still don't understand you- It's all this disco music.

**Comment by holke** [comment]
ok, then i misunderstood you.
I thought you meant it was a lot of work to make the smileys disappear and appear in the houses.
