### ISSUE TITLE
Implement level 2

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#79]
The player needs to get to the supermarket, grab some toilet paper and get home again.

**Comment by holke** [comment]
What this has in common with #80 is a kind of inventory system for things the player can collect.
Here it’s toilet paper, in the other level it’s face masks.
Think this can be done quite easily by storing a list of integers in the player class, one for each type of item corresponding to the number of items the player has.
Then a add item and remove item function and we should be done.
Let’s just not do the work twice and once one of us has it implemented tell the others.

**Comment by holke** [comment]
See issue #86 for the inventory

**Comment by maccxs** [comment]
Hey,

first well working verison of the level testable: 
https://github.com/youvsvirus/youvsvirus-unity/tree/levelsupermarket

I still have to work on some kinks:
- blinking toilet paper
- sometimes the travelling agents trap the non-ai smileys
- lots of cleaning an ordering of the scripts to do!

Feedback is highly welcome!
