### ISSUE TITLE
Sandbox mode

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#81]
The current version of the game should be available as a sandbox mode.
Add an option to the menu.

**Comment by maccxs** [comment]
I tried this out, my proposal would be a new Main Menu, where you can either go to Sandbox or Start the levels:
Two buttons: Campaign and Explore (other names?)
On mouse over, these buttons show explanations for the user, like
Campaign: Start your adventure against the virus
Explore: Explore the effects of social distancing and population distance
?

**Comment by holke** [comment]
I like. Especially the idea with mouse mover.
Currently, I don’t have better names but maybe we find some innrer future.

**Comment by holke** [comment]
How will the end screen of sandbox be?
 should it lead the user back to the sandbox mode, not back to the complete beginning?
But maybe it’s ok to choose each time....
Since otherwise we need two buttons, one back to sandbox mode, one to the campaign...
