### ISSUE TITLE
End screens of levels are missing smileys.

### ISSUE THREAD

**Issue by holke** [youvsvirus/youvsvirus-unity#99]
The end screens of the levels do not have the smiley pictures from #77 in them, but are still the old non-smiley end screen.
We should fix this.

**Comment by maccxs** [comment]
Yes, but we do not know how this end screen will look like. Due to the shorter time scale, etc. maybe the statistics only make sense for the sandbox or at that point when we track infections over all levels.

**Comment by holke** [comment]
Yes indeed. But when we decide to keep them, we should remember the smileys.

**Comment by holke** [comment]
Close because either done or not relevant.
